name: seddit
description: "A Reddot Clone for Android and iOS."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sidebarx: ^0.17.1
  flutter_local_notifications: ^17.2.1
  mongo_dart: ^0.10.3
  uuid: ^4.4.0
  flutter_dotenv: ^5.1.0
  provider: ^6.1.2
  flutter_markdown: ^0.7.3
  image_picker: ^1.1.2
  shake_detector_android: ^0.0.4
  firebase_ui_auth: ^1.15.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  firebase_dynamic_links: ^6.0.2
  flutter_secure_storage: ^4.2.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/images/
  - .env
